site_name: ShareCloud
site_url: https://example.com/
nav:
  - Avaleht: index.md
  - Tooted:
    - Starter Intra: products/starter.md
    - Puhkused: products/vacations.md

  - _Juhendid:
    #- manuals/index.md
    - Puhkused: manuals/vacations.md
    - DHS: manuals/dms.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  language: et
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
  
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/sharecloud/