site_name: ShareCloud docs
site_url: https://example.com/
nav:
  - Avaleht: index.md
  - Lahendused:
    - Starter-Intra: products/starter.md
    - Puhkused: products/vacations.md
    - Dokumendihaldus: products/dms.md
    - Digiallkirjastamine: products/digitalSigning.md
    - Digiallkirjastamine välise osapoolega: products/digitalSigningExternal.md
    - Pildigalerii: products/picturegallery.md
    - Ettevõtte struktuur: products/orgStructure.md
    - E-maili signatuur: products/signature.md
    - Üritused ja koolitused: products/eventsAndTrainings.md
    - Kasutajate haldus: products/usersManagement.md

  - _Juhendid:
    #- manuals/index.md
    - Puhkused: manuals/vacations.md
    - DHS: manuals/dms.md

theme:
  name: material
  font:
    text: Roboto
  palette:
    primary: blue
    accent: deep orange
  favicon: img/favicon.ico
  custom_dir: overrides
  logo: assets/logo.png
  language: et
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
  
extra:
  homepage: https://sharecloudoy.github.io
  generator: false
  social:
    - icon: fontawesome/solid/cloud
      link: https://sharecloud.ee
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/sharecloud/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ShareCloudOU
copyright: Copyright &copy; 2024 
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
